## Verilerin istatistiksel olarak incelenmesi ve ayrık değerlerin ayıklanması

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   city          8136 non-null   object
 1   district      8136 non-null   object
 2   neighborhood  8136 non-null   object
 3   room          8136 non-null   int64
 4   living_room   8136 non-null   int64
 5   m²            8136 non-null   int64
 6   age           8136 non-null   int64
 7   floor         8136 non-null   int64
 8   price         8136 non-null   int64
dtypes: int64(6), object(3)
memory usage: 572.2+ KB

In [4]:
df['city'] = df['city'].astype('category')
df['district'] = df['district'].astype('category')
df['neighborhood'] = df['neighborhood'].astype('category')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   city          8136 non-null   category
 1   district      8136 non-null   category
 2   neighborhood  8136 non-null   category
 3   room          8136 non-null   int64
 4   living_room   8136 non-null   int64
 5   m²            8136 non-null   int64
 6   age           8136 non-null   int64
 7   floor         8136 non-null   int64
 8   price         8136 non-null   int64
dtypes: category(3), int64(6)
memory usage: 438.2 KB

Nümerik değişkenlerin minimum, maxsimum ve çeyreklik değerlerinin bulunması:

In [6]:
columns = df.select_dtypes(include='number').columns
min_values = []
max_values = []
for column in columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    min_value = Q1 - 1.5 * IQR
    max_value = Q3 + 1.5 * IQR
    min_values.append(min_value)
    max_values.append(max_value)
    print(f"column: {column}, min: {min_value}, max: {max_value}")

column: room, min: 0.5, max: 4.5
column: living_room, min: 1.0, max: 1.0
column: m², min: -17.5, max: 242.5
column: age, min: -20.0, max: 44.0
column: floor, min: -2.0, max: 6.0
column: price, min: -18000.0, max: 62000.0

Aykırı değerlerin temizlenmesi

In [ ]:
for i, column in enumerate(columns): # enumerate bize index'inde dönmesini sağlar.
    print(f"column:{column}, min_value:{min_values[i]}, max_value:{max_values[i]}")

column:room, min_value:0.5, max_value:4.5
column:living_room, min_value:1.0, max_value:1.0
column:m², min_value:-17.5, max_value:242.5
column:age, min_value:-20.0, max_value:44.0
column:floor, min_value:-2.0, max_value:6.0
column:price, min_value:-18000.0, max_value:62000.0

In [12]:
# bizim buradaki amacımız çok büyük ve çok küçük verileri temizlemek. Bunu da şu şekilde yapacağız:
for i, column in enumerate(columns):
    df = df[(df[column]>=min_values[i]) & (df[column] <= max_values[i])]

In [ ]:
df.info() # toplam veri 8136 dan 6212 ye düşmüş oldu. Aykırı değerler bu şekilde elenmiş oldu.

<class 'pandas.core.frame.DataFrame'>
Index: 6212 entries, 0 to 8135
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   city          6212 non-null   category
 1   district      6212 non-null   category
 2   neighborhood  6212 non-null   category
 3   room          6212 non-null   int64
 4   living_room   6212 non-null   int64
 5   m²            6212 non-null   int64
 6   age           6212 non-null   int64
 7   floor         6212 non-null   int64
 8   price         6212 non-null   int64
dtypes: category(3), int64(6)
memory usage: 388.9 KB

şimdi veriyi daha iyi inceleyebilmek için describe metot'unu kullanabiliriz:

In [14]:
df.describe()

,room,living_room,m²,age,floor,price
count,6212.000000,6212.0,6212.000000,6212.000000,6212.000000,6212.000000
mean,2.176272,1.0,104.669350,12.653896,2.199614,17900.975853
std,0.826815,0.0,39.442494,10.451565,1.589618,10467.582893
min,1.000000,1.0,5.000000,0.000000,-2.000000,1.000000
25%,2.000000,1.0,75.000000,4.000000,1.000000,11000.000000
50%,2.000000,1.0,100.000000,10.000000,2.000000,15000.000000
75%,3.000000,1.0,130.000000,20.000000,3.000000,21000.000000
max,4.000000,1.0,240.000000,44.000000,6.000000,60000.000000

Gördüğümüz gibi price haricinde diğerlerinde sıkıntı yok. Pricedaki sıkıntı şu kirası 1 TL olan bir bina olamayacağı için min value'sı hatalı

In [17]:
df = df[df['price'] >= 3000]

In [19]:
df.info() # şimdi ise verilerimiz 6212 den 6116'ya düşmüş oldu.

<class 'pandas.core.frame.DataFrame'>
Index: 6116 entries, 0 to 8135
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   city          6116 non-null   category
 1   district      6116 non-null   category
 2   neighborhood  6116 non-null   category
 3   room          6116 non-null   int64
 4   living_room   6116 non-null   int64
 5   m²            6116 non-null   int64
 6   age           6116 non-null   int64
 7   floor         6116 non-null   int64
 8   price         6116 non-null   int64
dtypes: category(3), int64(6)
memory usage: 383.3 KB

In [20]:
df.describe()

,room,living_room,m²,age,floor,price
count,6116.000000,6116.0,6116.000000,6116.000000,6116.000000,6116.000000
mean,2.180020,1.0,104.830445,12.698169,2.198496,18170.733976
std,0.826463,0.0,39.467687,10.465384,1.589161,10323.229150
min,1.000000,1.0,5.000000,0.000000,-2.000000,3000.000000
25%,2.000000,1.0,75.000000,4.000000,1.000000,11500.000000
50%,2.000000,1.0,100.000000,10.000000,2.000000,15000.000000
75%,3.000000,1.0,130.000000,20.000000,3.000000,21000.000000
max,4.000000,1.0,240.000000,44.000000,6.000000,60000.000000

In [21]:
df.to_csv('data_cleaned.csv', index=False)